// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqUeqExzpAOLHppPlI8nGUefA3z-Tiy1U',
    appId: '1:538040643821:web:b066cfa78d5c1962349ce4',
    messagingSenderId: '538040643821',
    projectId: 'redhouse-b61f4',
    authDomain: 'redhouse-b61f4.firebaseapp.com',
    storageBucket: 'redhouse-b61f4.appspot.com',
    measurementId: 'G-1KFZ73FZJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUibetIn4R1WkUl4chxYWrWqlQQZvdbts',
    appId: '1:538040643821:android:707da814f222a443349ce4',
    messagingSenderId: '538040643821',
    projectId: 'redhouse-b61f4',
    storageBucket: 'redhouse-b61f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8fUpKZBwp4TG7eJoBXmXia7a6S3frsiY',
    appId: '1:538040643821:ios:005d12f4866a823d349ce4',
    messagingSenderId: '538040643821',
    projectId: 'redhouse-b61f4',
    storageBucket: 'redhouse-b61f4.appspot.com',
    iosBundleId: 'com.example.client',
  );
}
